"""
Reporting module for backtesting results.
Generates formatted reports from backtesting output.
"""

from typing import List, Dict
import sys
import os

# Add the backtest directory to path for imports
sys.path.append(os.path.dirname(__file__))

from metrics import calculate_metrics, calculate_trade_durations, calculate_monthly_returns


def generate_report(
    trades: List[Dict],
    equity_curve: List[float],
    timestamps: List[str],
    initial_capital: float = 100000.0,
    symbol: str = "MULTIPLE",
    timeframe: str = "1D",
    start_date: str = "",
    end_date: str = "",
    signals_generated: int = 0
) -> str:
    """
    Generate a formatted text report from backtesting results.

    Args:
        trades: List of completed trade dictionaries
        equity_curve: List of capital values over time
        timestamps: Corresponding timestamps for equity curve
        initial_capital: Starting capital
        symbol: Primary symbol tested (or "MULTIPLE")
        timeframe: Data timeframe used
        start_date: Backtest start date
        end_date: Backtest end date

    Returns:
        Formatted report string
    """
    if not trades:
        return generate_empty_report(symbol, timeframe, start_date, end_date)

    # Calculate metrics
    metrics = calculate_metrics(trades, initial_capital)
    avg_duration, median_duration = calculate_trade_durations(trades)
    monthly_returns = calculate_monthly_returns(trades, initial_capital)

    # Build report
    report_lines = []

    # Header
    report_lines.append("=" * 60)
    report_lines.append("SWING TRADING STRATEGY BACKTEST REPORT")
    report_lines.append("=" * 60)
    report_lines.append(f"Symbol: {symbol}")
    report_lines.append(f"Timeframe: {timeframe}")
    if start_date and end_date:
        report_lines.append(f"Period: {start_date} to {end_date}")
    report_lines.append(f"Initial Capital: ₹{initial_capital:,.2f}")
    report_lines.append(f"Signals Generated: {signals_generated}")
    report_lines.append("")

    # Performance Metrics
    report_lines.append("PERFORMANCE METRICS:")
    report_lines.append("-" * 20)
    report_lines.append(f"Total Return: {metrics['total_return_pct']:+.2f}%")
    report_lines.append(f"Final Capital: ₹{metrics.get('total_return', 0) + initial_capital:,.2f}")
    report_lines.append(f"Total Trades: {int(metrics['total_trades'])}")
    report_lines.append(f"Win Rate: {metrics['win_rate']:.2f}%")
    report_lines.append(f"Profit Factor: {metrics['profit_factor']:.2f}")
    report_lines.append(f"Sharpe Ratio: {metrics['sharpe_ratio']:.2f}")
    report_lines.append(f"Max Drawdown: {metrics['max_drawdown']:.2f}%")
    report_lines.append(f"Average Trade: {metrics['avg_trade_pct']:+.2f}%")
    report_lines.append(f"Average Win: {metrics['avg_win_pct']:+.2f}%")
    report_lines.append(f"Average Loss: {metrics['avg_loss_pct']:+.2f}%")
    report_lines.append(f"Expectancy: {metrics['expectancy']:+.2f}% per trade")
    report_lines.append(f"Avg Trade Duration: {avg_duration:.1f} hours")
    report_lines.append(f"Median Trade Duration: {median_duration:.1f} hours")
    report_lines.append("")

    # Trade List
    report_lines.append("TRADE LIST:")
    report_lines.append("-" * 20)
    report_lines.append(f"{'#':<4} {'Symbol':<8} {'Action':<6} {'Entry':<10} {'Exit':<10} "
                       f"{'P&L (₹)':<12} {'P&L (%)':<10} {'Duration':<10} {'Reason':<12}")
    report_lines.append("-" * 90)

    for i, trade in enumerate(trades, 1):
        duration_str = f"{trade.get('duration_hours', 0):.1f}h"
        report_lines.append(
            f"{i:<4} {trade['symbol']:<8} {trade['action']:<6} "
            f"₹{trade['entry_price']:<9.2f} ₹{trade['exit_price']:<9.2f} "
            f"₹{trade['pnl']:<11.2f} {trade['pnl_pct']:<+9.2f}% "
            f"{duration_str:<10} {trade.get('exit_reason', 'N/A'):<12}"
        )

    report_lines.append("")

    # Equity Curve Summary
    report_lines.append("EQUITY CURVE SUMMARY:")
    report_lines.append("-" * 22)
    report_lines.append(f"Starting Equity: ₹{initial_capital:,.2f}")
    report_lines.append(f"Ending Equity: ₹{equity_curve[-1]:,.2f}")
    report_lines.append(f"Peak Equity: ₹{max(equity_curve):,.2f}")
    report_lines.append(f"Trough Equity: ₹{min(equity_curve):,.2f}")
    report_lines.append("")

    # Monthly Returns (if available)
    if monthly_returns:
        report_lines.append("MONTHLY RETURNS:")
        report_lines.append("-" * 16)
        for month in sorted(monthly_returns.keys()):
            ret = monthly_returns[month]
            report_lines.append(f"{month}: {ret:+.2f}%")
        report_lines.append("")

    # Footer
    report_lines.append("=" * 60)
    report_lines.append("Report generated by Swing Trading Backtesting Module")
    report_lines.append("=" * 60)

    return "\n".join(report_lines)


def generate_empty_report(
    symbol: str,
    timeframe: str,
    start_date: str,
    end_date: str
) -> str:
    """
    Generate report when no trades were executed.
    """
    report_lines = []
    report_lines.append("=" * 60)
    report_lines.append("SWING TRADING STRATEGY BACKTEST REPORT")
    report_lines.append("=" * 60)
    report_lines.append(f"Symbol: {symbol}")
    report_lines.append(f"Timeframe: {timeframe}")
    if start_date and end_date:
        report_lines.append(f"Period: {start_date} to {end_date}")
    report_lines.append("")

    report_lines.append("RESULT: NO TRADES EXECUTED")
    report_lines.append("")
    report_lines.append("Possible reasons:")
    report_lines.append("- Insufficient data for indicator calculation")
    report_lines.append("- Strategy conditions not met during test period")
    report_lines.append("- Timeframe too short for signals to develop")
    report_lines.append("- Market conditions unfavorable for strategy")
    report_lines.append("")
    report_lines.append("=" * 60)

    return "\n".join(report_lines)


def save_report(report: str, filename: str):
    """
    Save report to a file.

    Args:
        report: Report string to save
        filename: Output filename
    """
    try:
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(report)
        print(f"[INFO] Report saved to {filename}")
    except Exception as e:
        print(f"[ERROR] Failed to save report: {e}")


if __name__ == "__main__":
    # Test the report generator
    print("Testing report generator...")

    # Sample trade data for testing
    sample_trades = [
        {
            'symbol': 'RELIANCE',
            'action': 'BUY',
            'entry_price': 2500.0,
            'exit_price': 2600.0,
            'quantity': 40,
            'pnl': 4000.0,
            'pnl_pct': 4.0,
            'entry_time': '2026-06-01 10:00:00',
            'exit_time': '2026-06-05 15:00:00',
            'duration_hours': 101.0,
            'exit_reason': 'TAKE_PROFIT'
        },
        {
            'symbol': 'TCS',
            'action': 'SELL',
            'entry_price': 3500.0,
            'exit_price': 3400.0,
            'quantity': 30,
            'pnl': 3000.0,
            'pnl_pct': 2.86,
            'entry_time': '2026-06-10 09:30:00',
            'exit_time': '2026-06-12 14:15:00',
            'duration_hours': 52.75,
            'exit_reason': 'STOP_LOSS'
        }
    ]

    # Sample equity curve (simplified)
    sample_equity = [100000.0, 104000.0, 107000.0, 106500.0, 110000.0]
    sample_timestamps = [
        '2026-06-01 00:00',
        '2026-06-05 00:00',
        '2026-06-10 00:00',
        '2026-06-12 00:00',
        '2026-06-15 00:00'
    ]

    report = generate_report(
        trades=sample_trades,
        equity_curve=sample_equity,
        timestamps=sample_timestamps,
        initial_capital=100000.0,
        symbol="RELIANCE, TCS",
        timeframe="1D",
        start_date="2026-06-01",
        end_date="2026-06-15"
    )

    print(report)